# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/leon3mp.xdc

# Block Designs: bd/leon3_zc702_stub/leon3_zc702_stub.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==leon3_zc702_stub || ORIG_REF_NAME==leon3_zc702_stub} -quiet] -quiet

# IP: bd/leon3_zc702_stub/ip/leon3_zc702_stub_processing_system7_0_0/leon3_zc702_stub_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==leon3_zc702_stub_processing_system7_0_0 || ORIG_REF_NAME==leon3_zc702_stub_processing_system7_0_0} -quiet] -quiet

# XDC: bd/leon3_zc702_stub/ip/leon3_zc702_stub_processing_system7_0_0/leon3_zc702_stub_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==leon3_zc702_stub_processing_system7_0_0 || ORIG_REF_NAME==leon3_zc702_stub_processing_system7_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/leon3_zc702_stub/leon3_zc702_stub_ooc.xdc
