# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.cache/wt [current_project]
set_property parent.project_path /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_property ip_output_repo /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library grlib {
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/stdlib/config_types.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/stdlib/config.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/stdlib/version.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/stdlib/stdlib.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/amba.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/devices.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/ahbctrl.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/ahbmst.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/apbctrl.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/amba/apbctrlx.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/sparc/sparc.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/modgen/leaves.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/grlib/modgen/multlib.vhd
}
read_vhdl -library techmap {
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/gencomp/gencomp.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/allclkgen.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/allmem.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/allmul.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/allpads.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/alltap.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/unisim/buffer_unisim.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/clkand.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/unisim/clkgen_unisim.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/clkmux.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/grfpw_net.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/gencomp/netcomp.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/grgates.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/grlfpw_net.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/inpad.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/iopad.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/leon3_net.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/inferred/memory_inferred.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/unisim/memory_unisim.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/memrwcol.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/inferred/mul_inferred.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/outpad.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/unisim/pads_unisim.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/regfile_3p.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/syncram.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/syncram64.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/syncram_2p.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/syncram_dp.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/syncrambw.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/tap.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/unisim/tap_unisim.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/techbuf.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/techmap/maps/techmult.vhd
}
read_vhdl -library gaisler {
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/axi/axi.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/axi/ahb2axi3b.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/misc/misc.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/axi/ahb2axib.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/jtag/libjtagcom.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/jtag/jtag.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/jtag/ahbjtag.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/misc/ahbram.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/misc/ahbstat.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/uart/uart.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/uart/apbuart.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/arith/arith.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3/leon3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/libfpu.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmuconfig.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/libiu.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmuiface.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/libcache.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/cachemem.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/cmvalidbits.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/arith/div32.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/dsu3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/dsu3x.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/misc/gptimer.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/libleon3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/grfpwx.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/grfpwxsh.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/misc/grgpio.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/grlfpwx.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/irqmp/irqmp.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/iu3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/jtag/jtagcom.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/jtag/jtagcom2.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/leon3s.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/leon3x.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/libmmu.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmu.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/mmu_acache.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/mmu_cache.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/mmu_dcache.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/mmu_icache.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmulru.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmulrue.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmutlb.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmutlbcam.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/srmmu/mmutw.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/arith/mul32.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/proc3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/regfile_3p_l3.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/tbufmem.vhd
  /home/kris/riscvy-business/grlib-2018.3/lib/gaisler/leon3v3/tbufmem_2p.vhd
}
read_vhdl -library xil_defaultlib {
  /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/ahbrom.vhd
  /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/config.vhd
  /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/leon3mp.vhd
}
add_files /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.srcs/sources_1/bd/leon3_zc702_stub/leon3_zc702_stub.bd
set_property used_in_implementation false [get_files -all /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.srcs/sources_1/bd/leon3_zc702_stub/ip/leon3_zc702_stub_processing_system7_0_0/leon3_zc702_stub_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/vivado/leon3-zc702/leon3-zc702.srcs/sources_1/bd/leon3_zc702_stub/leon3_zc702_stub_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/leon3mp.xdc
set_property used_in_implementation false [get_files /home/kris/riscvy-business/grlib-2018.3/designs/leon3-xilinx-zc702/leon3mp.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top leon3mp -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef leon3mp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file leon3mp_utilization_synth.rpt -pb leon3mp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
