---
- name: Configure standardized development server on base Ubuntu 18.04 LTS.
  hosts: devserver
  become: true
  become_user: {{ USER }}
  any_errors_fatal: true


  tasks:
  # TODO: Version freeze the packages when installed for the first time.
  - name: Get relevant build packages
    apt:
      name:
        - autoconf
        - automake
        - autotools-dev
        - bc
        - bison
        - build-essential
        - curl
        - default-jdk
        - device-tree-compiler
        - flex
        - gawk
        - git
        - gperf
        - g++
        - libexpat1-dev
        - libgmp-dev
        - libmpc-dev
        - libmpfr-dev
        - libtool
        - make
        - patchutils
        - pkg-config
	- tcl
        - texinfo
        - zlib1g-dev
      state: latest

  - name: Clone Riscvy-business repository, which contains specific versions of GRLIB and Rocket Chip Generator
    git:
      repo: https://github.com/N35N0M/riscvy-business.git
      dest: "{{ USER_HOME }}/riscvy-business"
      recursive: true
      version: HEAD
      force: true
      
  - name: Give set user file ownership of repository. Needed for building GRLIB designs, amongst other things.
    file:
    	path: "{{ USER_HOME }}/riscvy-business"
    	owner: {{ USER }}
    	group: {{ USER }}
        recurse: {{ USER }}

  - name: Check if RISC-V tools already exist.
    stat:
      path: /opt/riscv32i
    register: toolsinstalled

  - name: Download RISC-V tools via Makefile provided in picorv32
    command: /usr/bin/make download-tools
    args:
      chdir: "{{ USER_HOME }}/riscvy-business/picorv32" 
    when: "not toolsinstalled.stat.exists"

  - name: Build all relevant variants of the RISC-V tools via picorv32 Makefile
    shell: /bin/echo "YES" | /usr/bin/make -j$(nproc) build-tools
    args:
      chdir: "{{ USER_HOME }}/riscvy-business/picorv32" 
    when: "not toolsinstalled.stat.exists"
    become: true

  - name: Add path to relevant build tool set to user's .bashrc . Must be either sourced or restart user session.
    lineinfile:
      path: "{{ USER_HOME }}/.bashrc"
      state: present
      line: "PATH=$PATH:/opt/riscv32i/bin"
